services:

  db:
    image: postgres
    restart: always
    hostname: db
    environment:
      POSTGRES_USER: richi
      POSTGRES_PASSWORD: test

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
